server:
  port: 8080
spring:
  application:
     name: edm-api
edm:
  jwt:
    secret: asdfasdfasdfasdfasdfasdfasdfasdf
    expiration: 100000000000
  api:
    credentials:
      username: EDM-API@EDM.COM
      password: EDM-API111

grpc:
  indexer:
    host: localhost
    port: 8136



