server:
  port: 8080
spring:
  application:
     name: edm-api
edm:
  jwt:
    secret: NAhospQgZJWzJwf4tVX3Ig8G04v1tKX5
    expiration: 3600000
  api:
    credentials:
      email: EDM-API@EDM.COM
      password: EDM-API111
  core:
    url: http://localhost:8082
grpc:
  indexer:
    host: localhost
    port: 8136





